# -*- coding: utf-8 -*-
"""DCNN_22_on_CK+_dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sh9QSBiPtDWS01jj0y-8AIrVrlM8oVv4

# libraries, data input and preprocessing
"""

pip install keras-visualizer

import numpy as np
import pandas as pd
import os,cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

import tensorflow as tf
import tensorflow.keras as keras
from keras_visualizer import visualizer
from tensorflow.keras import callbacks
from tensorflow.keras import utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Activation , Dropout ,Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from tensorflow.keras.metrics import categorical_accuracy
from tensorflow.keras.models import model_from_json
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import *
from keras.layers import BatchNormalization
import os
from sklearn.metrics import classification_report

from google.colab import drive
drive.mount('/content/gdrive')

data_path = '/content/gdrive/MyDrive/CK+48'
data_dir_list = os.listdir(data_path)

img_data_list=[]
img_class = 0
labels = []
names = []

for dataset in data_dir_list:
    img_list=os.listdir(data_path+'/'+ dataset)
    print ('Loaded the images of dataset-'+'{}\n'.format(dataset))
    names.append(dataset)
    for img in img_list:
        input_img=cv2.imread(data_path + '/'+ dataset + '/'+ img )
        input_img=cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY)
        input_img_resize=cv2.resize(input_img,(48,48))
        img_data_list.append(input_img_resize)
        labels.append(img_class)
    img_class += 1

img_data = np.array(img_data_list)
img_data = img_data.astype('float32')
img_data = img_data/255
img_data.shape
num_classes = img_class
Y = utils.to_categorical(labels, num_classes)

def getLabel(id):
    return names[id]

X_train, X_test, y_train, y_test = train_test_split(img_data, Y, test_size=0.20, shuffle=True, random_state=42)

X_train = np.reshape(X_train, (X_train.shape[0], 48, 48, 1))
X_test = np.reshape(X_test, (X_test.shape[0], 48, 48, 1))

print(X_train.shape)
print(X_test.shape)

"""# model"""

#load the libaray to built the model
from keras.layers import Activation, Convolution2D, Dropout, Conv2D
from keras.layers import AveragePooling2D, BatchNormalization
from keras.layers import GlobalAveragePooling2D
from keras.models import Sequential
from keras.layers import Flatten
from keras.models import Model
from keras.layers import Input
from keras.layers import MaxPooling2D
from keras.layers import SeparableConv2D
from keras import layers
from keras.regularizers import l2

input_shape=(48,48,1)

""" Building up Model Architecture """

model = Sequential()
model.add(Convolution2D(filters=64, kernel_size=(5, 5), padding='same', kernel_initializer='he_normal', activation='relu',
                            name='image_array', input_shape=input_shape))
model.add(BatchNormalization())
model.add(Convolution2D(filters=64, kernel_size=(5, 5), padding='same', kernel_initializer='he_normal',activation='relu',))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
model.add(Dropout(.5))

model.add(Convolution2D(filters=128, kernel_size=(3, 3), padding='same', kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=128, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
model.add(Dropout(.5))

model.add(Convolution2D(filters=256, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=256, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=256, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=256, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=256, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
model.add(Dropout(.5))

model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal',activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
model.add(Dropout(.5))

model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(Convolution2D(filters=512, kernel_size=(3, 3), padding='same',kernel_initializer='he_normal', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
model.add(Flatten())

model.add(Dense(units=128,activation='relu'))
model.add(BatchNormalization())
model.add(Dense(units=128,activation='relu'))
model.add(BatchNormalization())
model.add(Dense(units=7,activation='softmax'))
model.summary()

"""## compile and fit model"""

filename='model_train_new.csv'
filepath = os.path.join("./emotion_detector_models_ck+/model_v6_{epoch}.hdf5")

checkpoint = keras.callbacks.ModelCheckpoint(filepath,
                                             monitor='val_accuracy',
                                             verbose=1,
                                             save_best_only=True,
                                             mode='max')

csv_log=callbacks.CSVLogger(filename, separator=',', append=False)
checkpoint = callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [csv_log,checkpoint]
callbacks_list = [csv_log]

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy', 'MeanSquaredError'])

model_info = model.fit(X_train, y_train, batch_size=32, epochs=80, validation_data=(X_test, y_test), callbacks=callbacks_list)



"""## score and plots"""

score = model.evaluate(X_train, y_train)
print('Accuracy (train): %.2f' % (score[1]*100))

score = model.evaluate(X_test, y_test)
print('Accuracy (test): %.2f' % (score[1]*100))

plt.plot(model_info.history['loss'], 'r', label='train')
plt.plot(model_info.history['val_loss'], 'b', label='test')
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend()
plt.show()

plt.plot(model_info.history['accuracy'], 'r', label='train')
plt.plot(model_info.history['val_accuracy'], 'b', label='test')
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend()
plt.show()

y_pred = np.argmax(model.predict(X_test), axis=-1)

y_pred = utils.to_categorical(y_pred, num_classes)

print(classification_report(y_test, y_pred, target_names=names))

def title(y_pred, y_test, target_names, i):
    pred_name = names[y_pred[i]].rsplit(' ', 1)[-1]
    true_name = names[y_test[i]].rsplit(' ', 1)[-1]
    return 'predicted: %s\ntrue: %s' % (pred_name, true_name)

def plot_gallery(images, titles, h, w, n_row=3, n_col=4):
    """Helper function to plot a gallery of portraits"""
    plt.figure(figsize=(1.8 * n_col, 2.4 * n_row))
    plt.subplots_adjust(bottom=0, left=.01, right=.99, top=.90, hspace=.35)
    for i in range(n_row * n_col):
        plt.subplot(n_row, n_col, i + 1)
        plt.imshow(images[i].reshape((h, w)), cmap=plt.cm.gray)
        plt.title(titles[i], size=12)
        plt.xticks(())
        plt.yticks(())

y_pred = [np.where(i == 1)[0][0] for i in y_pred]
y_test = [np.where(i == 1)[0][0] for i in y_test]

prediction_titles = [title(y_pred, y_test, names, i) for i in range(len(y_pred))]
plot_gallery(X_test, prediction_titles, 48, 48)

# Create emotions map:
emotion_labels = [
    'Angry',
    'Disgust',
    'Fear',
    'Happy',
    'Sad',
    'Surprise',
    'Neutral'
]

# Predict using trained model:
y_pred = model.predict(X_train)
y_pred = np.asarray([np.argmax(e) for e in y_pred])
y_true = np.asarray([np.argmax(e) for e in y_train])

from sklearn.metrics import confusion_matrix
import seaborn as sns


# Compute confusion matrix:
cm = confusion_matrix(y_true, y_pred)
cm_normalised = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

# Plot confusion matrix:
sns.set(font_scale=1.5)
fig, ax = plt.subplots(figsize=(10,10))
ax = sns.heatmap(cm_normalised, annot=True, linewidths=0, square=False,
                 cmap='gray', yticklabels=emotion_labels,
                 xticklabels=emotion_labels, vmin=0,
                 vmax=np.max(cm_normalised), fmt=".2f",
                 annot_kws={"size": 20})
ax.set(xlabel='Predicted label', ylabel='True label')
