# -*- coding: utf-8 -*-
"""Preprocessing_(normalization,_face_detection_and_facial_landmark_detection).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uzzu1MAb0VO9-v7gZRPgeywZxI5l__Iu
"""

from google.colab import drive
drive.mount('/content/gdrive')

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
from skimage import io
from PIL import Image
import matplotlib.pylab as plt

image = cv2.imread("/content/gdrive/MyDrive/datasets/facial lanmarks 3.PNG")
image_norm = cv2.normalize(image, None, alpha=0,beta=200, norm_type=cv2.NORM_MINMAX)

cv2_imshow( image)
cv2_imshow( image_norm)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Necessary imports
import cv2
import dlib
import numpy as np
from google.colab.patches import cv2_imshow
# Loading the image and converting it to grayscale
img= cv2.imread('/content/gdrive/MyDrive/datasets/facial lanmarks 3.PNG')
image_norma = cv2.normalize(image, None, alpha=0,beta=200, norm_type=cv2.NORM_MINMAX)
gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Initialize dlib's face detector
detector = dlib.get_frontal_face_detector()
# Detecting faces in the grayscale image
faces = detector(gray)
print(faces)

# Creating a for loop in order to extract
# specific coordinates (x1,x2,y1,y2)
for face in faces:
  x1=face.left()
  y1=face.top()
  x2=face.right()
  y2=face.bottom()
# Drawing a rectangle around the face
  cv2.rectangle(image_norma, (x1,y1), (x2,y2),(0,255,0),3)
cv2_imshow(image_norma)

p = "shape_predictor_68_face_landmarks.dat"
# Initialize dlib's shape predictor
predictor = dlib.shape_predictor(p)
# Get the shape using the predictor
landmarks=predictor(gray, face)

# Defining x and y coordinates of a specific point
x=landmarks.part(31).x
y=landmarks.part(31).y
# Drawing a circle
cv2.circle(image_norma, (x, y), 3, (0, 0, 255), -1)
cv2_imshow(image_norma)

for n in range(0,68):
    x=landmarks.part(n).x
    y=landmarks.part(n).y
    cv2.circle(image_norma, (x, y), 2, (0, 0, 255), -1)
cv2_imshow(image_norma)

import cv2
import numpy as np

image = cv2.imread("/content/gdrive/MyDrive/datasets/ck+ facial landmarks 2.PNG")
image_norm = cv2.normalize(image, None, alpha=0,beta=200, norm_type=cv2.NORM_MINMAX)

cv2_imshow( image)
cv2_imshow( image_norm)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Necessary imports
import cv2
import dlib
import numpy as np
from google.colab.patches import cv2_imshow
# Loading the image and converting it to grayscale
img= cv2.imread('/content/gdrive/MyDrive/datasets/ck+ facial landmarks 2.PNG')
image_norm = cv2.normalize(image, None, alpha=0,beta=200, norm_type=cv2.NORM_MINMAX)
gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Initialize dlib's face detector
detector = dlib.get_frontal_face_detector()
# Detecting faces in the grayscale image
faces = detector(gray)
print(faces)

# Creating a for loop in order to extract
# specific coordinates (x1,x2,y1,y2)
for face in faces:
  x1=face.left()
  y1=face.top()
  x2=face.right()
  y2=face.bottom()
# Drawing a rectangle around the face
  cv2.rectangle(image_norm, (x1,y1), (x2,y2),(0,255,0),3)
cv2_imshow(image_norm)

!wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
!bunzip2 "shape_predictor_68_face_landmarks.dat.bz2"

p = "shape_predictor_68_face_landmarks.dat"
# Initialize dlib's shape predictor
predictor = dlib.shape_predictor(p)
# Get the shape using the predictor
landmarks=predictor(gray, face)

# Defining x and y coordinates of a specific point
x=landmarks.part(31).x
y=landmarks.part(31).y
# Drawing a circle
cv2.circle(image_norm, (x, y), 3, (0, 0, 255), -1)
cv2_imshow(image_norm)

for n in range(0,68):
    x=landmarks.part(n).x
    y=landmarks.part(n).y
    cv2.circle(image_norm, (x, y), 2, (0, 0, 255), -1)
cv2_imshow(image_norm)

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
from skimage import io
from PIL import Image
import matplotlib.pylab as plt

image = cv2.imread("/content/gdrive/MyDrive/Autistic/autism happy/0001.jpg")
gray=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image_norm = cv2.normalize(gray, None, alpha=0,beta=200, norm_type=cv2.NORM_MINMAX)

cv2_imshow( image)
cv2_imshow( image_norm)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Necessary imports
import cv2
import dlib
import numpy as np
from google.colab.patches import cv2_imshow
# Loading the image and converting it to grayscale
img= cv2.imread('/content/gdrive/MyDrive/Autistic/autism happy/0001.jpg')
image_norma = cv2.normalize(image, None, alpha=0,beta=200, norm_type=cv2.NORM_MINMAX)
gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Initialize dlib's face detector
detector = dlib.get_frontal_face_detector()
# Detecting faces in the grayscale image
faces = detector(gray)
print(faces)

# Creating a for loop in order to extract
# specific coordinates (x1,x2,y1,y2)
for face in faces:
  x1=face.left()
  y1=face.top()
  x2=face.right()
  y2=face.bottom()
# Drawing a rectangle around the face
  cv2.rectangle(image_norm, (x1,y1), (x2,y2),(0,0,128),3)
cv2_imshow(image_norm)

!wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
!bunzip2 "shape_predictor_68_face_landmarks.dat.bz2"

p = "shape_predictor_68_face_landmarks.dat"
# Initialize dlib's shape predictor
predictor = dlib.shape_predictor(p)
# Get the shape using the predictor
landmarks=predictor(gray, face)

# Defining x and y coordinates of a specific point
x=landmarks.part(31).x
y=landmarks.part(31).y
# Drawing a circle
cv2.circle(image_norm, (x, y), 3, (0, 0, 255), -1)
cv2_imshow(image_norm)

for n in range(0,68):
    x=landmarks.part(n).x
    y=landmarks.part(n).y
    cv2.circle(image_norm, (x, y), 2, (0, 0, 255), -1)
cv2_imshow(image_norm)
